'use client';

import DocsArticle from '../DocsArticle';
import DocsCallout from '../DocsCallout';
import DocsFeatureCard from '../DocsFeatureCard';
import DocsFeatureItem from '../DocsFeatureItem';

import * as data from '@/data/docs/guides/export-analytics.data';
import '../../../styles/components/docs/guides/ExportAnalyticsClient.scss';

const ExportAnalyticsClient = () => {
  return (
    <main className='export-analytics-client'>
      <DocsArticle
        category='Guides'
        title='Export Analytics'
        description='Learn how to export and preserve analytics generated by GitScope.'
        previous={{
          title: 'Compare Developers',
          href: '/documentation/guides/compare-developers',
        }}
        next={{
          title: 'Share a Profile',
          href: '/documentation/guides/share-profile',
        }}
      >
        <section id='overview'>
          <h2>Overview</h2>

          <p>
            GitScope provides analytics views that can be useful beyond the
            active browser session. The export workflow allows supported
            analytics to be preserved and used in other contexts.
          </p>

          <p>
            This guide explains how to approach exporting analytics, what to
            verify before using an exported result, and how to handle exported
            GitHub-related information responsibly.
          </p>

          <DocsCallout type='note'>
            Available export formats and controls depend on the current GitScope
            implementation. This guide does not assume a specific file format
            unless the application explicitly provides it.
          </DocsCallout>
        </section>

        <section id='what-can-be-exported'>
          <h2>What can be exported?</h2>

          <p>
            Exportable information depends on the GitScope analytics view you
            are using. The available result can include information presented by
            supported profile, repository, or comparison features.
          </p>

          <div className='export-analytics-client__grid'>
            {data.exportAreas.map((area) => (
              <DocsFeatureCard key={area.title} {...area} />
            ))}
          </div>
        </section>

        <section id='before-exporting'>
          <h2>Before exporting</h2>

          <p>
            Review the current analytics before creating an export. This helps
            you confirm that the profile, repository, or comparison is the one
            you intended to preserve.
          </p>

          <div className='export-analytics-client__list'>
            {data.exportReviews.map((review) => (
              <DocsFeatureItem key={review.title} {...review} />
            ))}
          </div>
        </section>

        <section id='export-workflow'>
          <h2>Export workflow</h2>

          <p>
            A simple workflow helps ensure that the exported result matches the
            analytics you intended to preserve.
          </p>

          <div className='export-analytics-client__list'>
            {data.exportWorkflow.map((step) => (
              <DocsFeatureItem key={step.title} {...step} />
            ))}
          </div>
        </section>

        <section id='using-exported-analytics'>
          <h2>Using exported analytics</h2>

          <p>
            Exported analytics can be useful when you need to reference GitScope
            results outside the application.
          </p>

          <div className='export-analytics-client__grid'>
            {data.exportAnalytics.map((analytic) => (
              <DocsFeatureCard key={analytic.title} {...analytic} />
            ))}
          </div>
        </section>

        <section id='exported-data-vs-live-analytics'>
          <h2>Exported data vs live analytics</h2>

          <p>
            An exported result represents the data available when the export was
            created. It does not necessarily update when the underlying GitHub
            profile or repository changes.
          </p>

          <p>
            Live GitScope analytics can therefore differ from an older exported
            result.
          </p>

          <DocsCallout type='warning'>
            When using exported analytics in a report or other document, include
            enough context to make clear when the data was generated.
          </DocsCallout>
        </section>

        <section id='privacy-and-exported-data'>
          <h2>Privacy and exported data</h2>

          <p>
            Exporting data creates a copy outside the immediate GitScope
            interface. You are responsible for handling that copy appropriately
            once it has been generated.
          </p>

          <div className='export-analytics-client__list'>
            {data.exportPrivacyData.map((item) => (
              <DocsFeatureItem key={item.title} {...item} />
            ))}
          </div>
        </section>

        <section id=''>
          <h2>Sharing an export</h2>

          <p>
            An exported result can be used as part of a broader sharing
            workflow. Before sharing it, verify that the information is
            appropriate for the intended audience.
          </p>

          <DocsCallout type='tip'>
            If you only need to give someone access to a GitScope analytics
            view, consider the application&apos;s sharing functionality instead
            of creating an additional copy of the data.
          </DocsCallout>
        </section>

        <section id=''>
          <h2>Export principles</h2>

          <p>
            Keep these principles in mind when creating and using GitScope
            exports.
          </p>

          <div className='export-analytics-client__list'>
            {data.exportPrinciples.map((principle) => (
              <DocsFeatureItem key={principle.title} {...principle} />
            ))}
          </div>
        </section>

        <section id='data-context'>
          <h2>Data context</h2>

          <p>
            GitScope analytics are derived from the GitHub data available to the
            application. Repository visibility, API limitations, permissions,
            and changes to GitHub data can affect what is included in an export.
          </p>

          <p>
            An export should therefore be treated as a snapshot of the available
            analytics rather than a permanent representation of the underlying
            GitHub account.
          </p>
        </section>

        <section id='next-steps'>
          <h2>Next steps</h2>

          <p>
            Continue with Share a Profile to learn how to share GitScope
            analytics with other people while keeping the shared context clear.
          </p>
        </section>
      </DocsArticle>
    </main>
  );
};

export default ExportAnalyticsClient;
